spring.application.name=ReportingService

# Setam un port unic, diferit de celelalte microservicii
server.port=8085

# URL-urile catre microserviciile de unde ReportingService isi ia datele
product.service.url=http://localhost:8082/api/produse
inventory.service.url=http://localhost:8083/api/inventory